
name: webclient-CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js & npm install & build
        uses: actions/setup-node@v2 
        with:
          node-version: '12.x'
          
      - name: npm install & build
        run: |
          npm install
          npm install -g @angular/cli
          ng build --prod
      
      #Publish artifacts-webclient
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wizard
          path: dist/wizard


